--- 
title: "Cancer Statistic"
author: "Yiquan Li, Chenxi Jiang, Zezhong Fan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In today's era, the impact of cancer on society has even reached the point that when someone is talking about cancer, others' faces will take on a ghastly expression. Cancer seriously affects the emotional, physical, and mental state of patients. In the years after cancer patients are diagnosed, their quality of life will drastically decrease. For the physiological side effects of advanced cancer treatment, such as impaired fertility, sexual dysfunction, hair loss, and weight gain, patients will feel inferior or even will be discriminated against.

Especially for families with poor financial status, not only must they consider whether they can afford medical expenses, but also how to face and deal with the despair and fear of death of cancer patients. Therefore, family members of cancer patients are also under tremendous psychological pressure, and their physical and mental health is also affected. Sometimes some patients cannot effectively control cancer pain with drugs, which will have a great impact on the patient's quality of life and psychological pressure, including anxiety, despair, and fear. Therefore, understanding and coping with the emotional, mental and physical trauma of cancer to humans will maximize the quality of life of cancer patients and their families. Modern medicine has invested considerable human and material resources in cancer research for a long time, and has gradually understood and understood the causes of cancer; the diagnosis of cancer has made considerable progress due to advances in science and technology. In order to alleviate everyone’s anxiety about cancer, we would like to learn more about cancer in different aspects, and see whether the world has really made progress against cancer and by how much in this project. Specifically, we will combine different data visualization methods and frames to explore the deeply current situation of cancer around the world and the progress in the medical realm against cancer.

In this projeect, three questions that we would like to persue are as follows:

- By how much is all kinds of cancer caused by genetic factors?
- What is the relationship between cancer survival rate and level of development (population, GDP, income, inequality, and so on) of a country?
- How does the world make propress against cancer over time?

To answer the questions above, we collected our cancer data from [*Global health Data Exchange*](http://ghdx.healthdata.org/gbd-results-tool?params=gbd-api-2019-public/27c2971bf0d3c792a091d314be89798f). The data souce we find includes data on many different aspect of cancer, including cancer prevalence, cancer mortality over time, causes of cancer and so on. From these data source, we can get the information that how cancer is relating to our world that it not only affects each family but also influence sundry countries. During this pandemic, the discussion one health problems should be on the agenda urgently. Via merging different tables, we can extract the data we need, and find the conclusion of our above cancer related questions.

Link to our book URL: https://maggieli99.github.io/Cancerstatistic.

This repo was initially generated from a bookdown template available here: https://github.com/jtr13/EDAVtemplate.